### ISSUE TITLE
It's really useful

### ISSUE THREAD

**Issue by zjkal** [SumoTTo/local-addon-tray#1]
Very useful, I have already used it.
Thank you very much!!!

**Comment by SumoTTo** [comment]
I'm glad you liked it.
Thank you for your feedback!

**Comment by arunbasillal** [comment]
Very grateful for this. I said this [already](https://community.localwp.com/t/add-windows-system-tray-support/3081/29?u=arun), but every time I use it I feel how good it is and wanted to say that again. Thank you so much.

**Comment by SumoTTo** [comment]
@arunbasillal I'm very glad that this is useful to you. Thanks for your feedback!
